version: "3.1"
services:
  nginx:
    image: "nginx"
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - hello-net
  hello-aqua:
    # hostname: aquahost
    build: 
      context: ./
      dockerfile: ./docker/aqua/Dockerfile
    ports:
      - "3001:3000"
    networks:
      - hello-net
  hello-magenta:
    # hostname: magentahost
    build: 
      context: ./
      dockerfile: ./docker/magenta/Dockerfile
    ports:
      - "3002:3000"
    networks:
      - hello-net

networks:
  hello-net: